version: "3"
services:
  learning-api:
    image: jeffrygonzalez/learning-resource-api:v0.1
    ports:
      - 1337:80
    environment:
      - ConnectionStrings__resources=server=sql;database=learning_prod;user=sa;password=TokyoJoe138!

  thank-you-api:
    image: jeffrygonzalez/thank-you-api:v0.2
    ports:
      - 1338:80
    environment:
      - ConnectionStrings__cards=server=sql;database=cards;user=sa;password=TokyoJoe138!
  sql:
    image: jeffrygonzalez/sql-intro-to-programming-jan2022:v2.0
    ports:
      - 1433:1433
